using DishDash.Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
namespace DishDash.Infrastructure;

public static class DemoSeed
{
    public static async Task Initialize(DishDashDbContext db, UserManager<AppUser> users, string? password)
    {
        if (!await db.Dishes.AnyAsync()) { db.Dishes.AddRange(CreateDishes()); await db.SaveChangesAsync(); }
        if (string.IsNullOrWhiteSpace(password) || await users.FindByEmailAsync("demo@dishdash.example") is not null) return;
        var user = new AppUser { UserName = "demo@dishdash.example", Email = "demo@dishdash.example" };
        var result = await users.CreateAsync(user, password);
        if (!result.Succeeded) throw new InvalidOperationException("The demo password must satisfy the configured password requirements.");
        db.Preferences.Add(new UserPreference { UserId = user.Id, DisplayName = "Alex", Cuisines = ["Indian", "Italian"] });
        db.Favorites.Add(new Favorite { UserId = user.Id, DishId = 1 });
        for (var i = 1; i <= 3; i++)
        {
            var dish = await db.Dishes.FindAsync(i) ?? throw new InvalidOperationException("Missing seed dish.");
            var created = DateTimeOffset.UtcNow.AddDays(-i);
            var order = new Order { UserId = user.Id, CheckoutKey = Guid.NewGuid(), CreatedAt = created, Total = 25 + i, Items = [new OrderItem { DishId = i, DishName = dish.Name, Servings = 2, Kind = i == 2 ? Fulfillment.Cook : Fulfillment.Restaurant, ProviderName = "Little Kitchen · Demo", Total = 25 + i }], Events = [new OrderStatusEvent { Status = OrderStatus.Confirmed, CreatedAt = created }] };
            for (var n = 0; n < 3; n++) order.Advance(created.AddMinutes(10 * (n + 1)));
            db.Orders.Add(order);
            db.Notifications.Add(new Notification { UserId = user.Id, OrderId = order.Id, CreatedAt = created.AddMinutes(30), Message = $"Your demo {dish.Name} order was delivered." });
            db.Ratings.Add(new Rating { UserId = user.Id, OrderId = order.Id, Stars = i == 2 ? 4 : 5, Comment = "A lovely demo meal." });
        }
        await db.SaveChangesAsync();
    }
    public static IReadOnlyList<Dish> CreateDishes()
    {
        var dishes = new List<Dish>();
        void Add(string name, string cuisine, string diet, string allergens, int prep, int cook, string effort, string photo, string description, string ingredients, params string[] steps)
        {
            dishes.Add(new Dish
            {
                Id = dishes.Count + 1,
                Name = name,
                Cuisine = cuisine,
                Diet = diet,
                Allergens = allergens.Split(',', StringSplitOptions.RemoveEmptyEntries),
                PrepMinutes = prep,
                CookMinutes = cook,
                Effort = effort,
                Image = photo,
                Description = description,
                Ingredients = ingredients.Split(';').Select(s => { var p = s.Split('|'); return new DishIngredient { Name = p[0], Quantity = decimal.Parse(p[1], System.Globalization.CultureInfo.InvariantCulture), Unit = p[2], BaseCost = decimal.Parse(p[3], System.Globalization.CultureInfo.InvariantCulture) }; }).ToList(),
                Steps = steps.Select((s, i) => { var p = s.Split('~'); return new CookingStep { Position = i + 1, Instruction = p[0], TimerSeconds = p.Length > 1 ? int.Parse(p[1]) : 0 }; }).ToList()
            });
        }
        Add("Butter Chicken", "Indian", "Omnivore", "milk", 15, 35, "Medium", "photo-1603894584373-5ac82b2ae398", "Tender chicken in a velvety tomato sauce, with warm spices and fluffy basmati rice.", "Chicken breast|300|g|4.20;Basmati rice|150|g|0.65;Tomato passata|200|ml|1.10;Cream|80|ml|0.90;Butter|20|g|0.35;Garam masala|8|g|0.30;Garlic|10|g|0.20",
            "Rinse the rice. Mince garlic and cut chicken into bite-sized pieces on a separate board.", "Simmer rice in water according to the packet. Melt butter and soften garlic with garam masala.~120", "Add chicken and passata. Simmer, stirring, until chicken reaches 74°C throughout.~1200", "Stir in cream, heat through and serve over rice.~180");
        Add("Garden Pesto Pasta", "Italian", "Vegetarian", "milk,wheat,tree nuts", 10, 15, "Easy", "photo-1473093295043-cdd812d0e601", "Basil, sweet tomatoes and parmesan make an easy, bright weeknight favourite.", "Pasta|180|g|0.90;Basil pesto|60|g|1.60;Cherry tomatoes|150|g|1.50;Parmesan|30|g|0.85;Olive oil|10|ml|0.20", "Boil a large pot of water. Halve tomatoes.", "Cook pasta according to the packet, reserving a cup of cooking water.~600", "Warm oil and tomatoes in a pan until softened.~240", "Toss pasta with pesto, tomatoes and a splash of pasta water. Finish with parmesan.");
        Add("Crispy Tofu Bowl", "Japanese", "Vegan", "soy,wheat,sesame", 15, 20, "Easy", "photo-1512621776951-a57141f2eefd", "Golden tofu, crunchy vegetables and sesame rice with a savoury soy dressing.", "Firm tofu|300|g|2.80;Rice|150|g|0.60;Broccoli|200|g|1.50;Carrot|100|g|0.40;Soy sauce|25|ml|0.25;Sesame oil|10|ml|0.30", "Press tofu dry and cube it. Slice the vegetables.", "Cook rice according to its packet.~900", "Pan-fry tofu in sesame oil, turning until golden. Steam broccoli and carrots until tender.~600", "Divide rice, tofu and vegetables between bowls and drizzle with soy sauce.");
        Add("Smoky Black Bean Tacos", "Mexican", "Vegan", "", 10, 15, "Easy", "photo-1551504734-5ee1c4a1479b", "Smoky beans, avocado and crisp slaw tucked into warm corn tortillas.", "Cooked black beans|300|g|1.20;Corn tortillas|6|pieces|1.80;Avocado|1|piece|1.30;Cabbage|100|g|0.40;Lime|1|piece|0.40;Smoked paprika|5|g|0.15", "Drain beans, shred cabbage and slice avocado.", "Heat beans with paprika and a splash of water, mashing some for texture.~480", "Warm tortillas in a dry pan, turning once.~120", "Fill tortillas with beans, cabbage and avocado. Finish with lime juice.");
        Add("Lemon Herb Salmon", "Mediterranean", "Pescatarian", "fish", 10, 25, "Medium", "photo-1467003909585-2f8a72700288", "Roasted salmon with lemon, tender potatoes and green beans.", "Salmon|300|g|7.50;Potatoes|300|g|0.80;Green beans|200|g|1.40;Lemon|1|piece|0.50;Olive oil|15|ml|0.30;Dried herbs|4|g|0.15", "Heat oven to 200°C. Cut potatoes into small wedges and toss with oil and herbs.", "Roast potatoes for 15 minutes before adding salmon to the tray.~900", "Top salmon with lemon. Roast until the fish reaches 63°C and potatoes are tender.~720", "Steam green beans until tender and serve alongside the salmon.~300");
        Add("Chickpea Coconut Curry", "Indian", "Vegan", "", 10, 25, "Easy", "photo-1547592180-85f173990554", "A comforting coconut curry with chickpeas, spinach and fragrant rice.", "Cooked chickpeas|300|g|1.20;Coconut milk|200|ml|1.20;Spinach|100|g|1.00;Rice|150|g|0.60;Curry powder|8|g|0.25;Onion|100|g|0.30", "Chop onion and rinse rice.", "Soften onion in a splash of coconut milk; stir in curry powder.~300", "Add chickpeas and remaining coconut milk. Simmer while rice cooks separately.~900", "Stir in spinach until wilted and serve with rice.~120");
        Add("Margherita Flatbread", "Italian", "Vegetarian", "wheat,milk", 10, 15, "Easy", "photo-1579751626657-72bc17010498", "Crisp flatbread topped with tomato, bubbling mozzarella and fresh basil.", "Flatbreads|2|pieces|1.80;Tomato sauce|120|ml|0.65;Mozzarella|125|g|2.20;Basil|10|g|0.70", "Preheat oven to 220°C and place flatbreads on a baking tray.", "Spread with tomato sauce and torn mozzarella.", "Bake until cheese bubbles and the edges are crisp.~600", "Scatter fresh basil over the hot flatbreads, slice and serve.");
        Add("Ginger Chicken Stir-fry", "Chinese", "Omnivore", "soy,wheat", 15, 15, "Medium", "photo-1512058564366-18510be2db19", "Quick-seared chicken and colourful peppers in a ginger-soy sauce.", "Chicken breast|300|g|4.20;Rice|150|g|0.60;Bell pepper|200|g|1.20;Ginger|15|g|0.20;Soy sauce|30|ml|0.30;Vegetable oil|15|ml|0.15", "Cook rice according to the packet. Slice peppers and mince ginger.", "Cut chicken separately. Stir-fry in hot oil until it reaches 74°C.~480", "Add peppers and ginger, stirring until vegetables are crisp-tender.~300", "Add soy sauce and a splash of water. Toss and serve over rice.");
        Add("Falafel Grain Bowl", "Mediterranean", "Vegan", "wheat,sesame", 15, 20, "Easy", "photo-1511690743698-d9d85f2fbf38", "Warm falafel, fluffy couscous and crunchy cucumber with tahini dressing.", "Prepared falafel|250|g|3.20;Couscous|150|g|0.80;Cucumber|150|g|0.70;Tomato|150|g|0.70;Tahini|30|g|0.55;Lemon|1|piece|0.50", "Heat falafel according to the packet, until piping hot throughout.~900", "Cover couscous with boiling water according to packet quantities and let stand.~300", "Dice cucumber and tomato. Whisk tahini with lemon juice and a little water.", "Fluff couscous, arrange falafel and vegetables on top, and drizzle with dressing.");
        Add("Peanut Noodle Salad", "Thai", "Vegan", "peanut,soy,wheat", 15, 10, "Easy", "photo-1569718212165-3a8278d5f624", "Cool noodles, crunchy vegetables and a tangy peanut-lime dressing.", "Rice noodles|180|g|1.30;Peanut butter|40|g|0.50;Carrot|100|g|0.40;Cucumber|150|g|0.70;Lime|1|piece|0.40;Soy sauce|20|ml|0.20", "Prepare noodles according to their packet, then rinse cool.~480", "Julienne carrot and cucumber.", "Whisk peanut butter, lime juice, soy sauce and warm water into a dressing.", "Toss noodles and vegetables with dressing and serve.");
        Add("Mushroom Risotto", "Italian", "Vegetarian", "milk", 10, 35, "Medium", "photo-1476124369491-e7addf5db371", "Slow-stirred arborio rice with golden mushrooms and parmesan.", "Arborio rice|160|g|1.00;Mushrooms|250|g|2.00;Vegetable stock|600|ml|0.70;Parmesan|40|g|1.10;Butter|25|g|0.45;Onion|100|g|0.30", "Slice mushrooms and onion. Heat stock in a separate saucepan.", "Soften onion and mushrooms in butter. Add rice and stir for 2 minutes.~420", "Add warm stock a ladle at a time, stirring until absorbed before adding more.~1500", "When rice is tender, stir in parmesan. Add a little stock to loosen and serve.");
        Add("Teriyaki Salmon Rice", "Japanese", "Pescatarian", "fish,soy,wheat", 10, 20, "Easy", "photo-1510130387422-82bed34b37e9", "Glossy teriyaki salmon over rice with steamed broccoli.", "Salmon|300|g|7.50;Rice|150|g|0.60;Broccoli|200|g|1.50;Teriyaki sauce|50|ml|0.70", "Cook rice according to its packet.~900", "Brush salmon with teriyaki sauce and bake at 200°C until it reaches 63°C.~900", "Steam broccoli until just tender.~300", "Serve salmon and broccoli over rice with the pan juices.");
        Add("Sweet Potato Burrito Bowl", "Mexican", "Vegan", "", 15, 30, "Easy", "photo-1540420773420-3366772f4999", "Roasted sweet potato, black beans and rice with a bright tomato salsa.", "Sweet potato|300|g|1.00;Cooked black beans|200|g|0.80;Rice|120|g|0.50;Tomato salsa|100|g|0.80;Olive oil|15|ml|0.30", "Heat oven to 210°C. Dice sweet potato and toss with oil.", "Roast sweet potato until tender and browned.~1500", "Cook rice according to its packet and warm beans in a saucepan.~900", "Build bowls with rice, beans and sweet potato. Spoon salsa on top.");
        Add("Thai Green Chicken Curry", "Thai", "Omnivore", "fish", 15, 25, "Medium", "photo-1455619452474-d2be8b1e70cd", "A fragrant green curry with chicken, coconut milk and tender vegetables.", "Chicken breast|300|g|4.20;Coconut milk|250|ml|1.50;Green curry paste|35|g|0.70;Green beans|150|g|1.00;Rice|150|g|0.60", "Slice chicken on a separate board. Trim beans and start rice according to the packet.", "Heat curry paste in a spoonful of coconut milk until fragrant.~120", "Add remaining coconut milk, chicken and beans. Simmer until chicken reaches 74°C.~1200", "Taste, stir well and serve curry with rice.");
        Add("Tomato Lentil Soup", "Mediterranean", "Vegan", "", 10, 30, "Easy", "photo-1547592166-23ac45744acd", "A hearty tomato and red lentil soup with carrots and warming spices.", "Red lentils|160|g|0.70;Canned tomatoes|400|g|1.10;Carrot|150|g|0.50;Onion|100|g|0.30;Vegetable stock|600|ml|0.70;Cumin|5|g|0.15", "Rinse lentils and dice onion and carrot.", "Soften vegetables in a little stock, then stir in cumin.~300", "Add lentils, tomatoes and remaining stock. Simmer until lentils are tender.~1500", "Mash lightly for a thicker texture, season to taste and serve.");
        Add("Korean Beef Rice Bowl", "Korean", "Omnivore", "soy,wheat,sesame", 15, 15, "Easy", "photo-1547592180-85f173990554", "Savoury ginger-soy beef, rice and quick-pickled cucumber.", "Ground beef|250|g|3.50;Rice|150|g|0.60;Cucumber|150|g|0.70;Soy sauce|25|ml|0.25;Sesame oil|10|ml|0.30;Ginger|10|g|0.15;Rice vinegar|20|ml|0.20", "Cook rice according to its packet. Thinly slice cucumber and toss with vinegar.", "Heat sesame oil and brown ground beef until it reaches 71°C.~480", "Stir in minced ginger and soy sauce; cook through.~180", "Spoon beef over rice and add cucumber on the side.");
        Add("Spinach Paneer", "Indian", "Vegetarian", "milk", 15, 25, "Medium", "photo-1631452180519-c014fe946bc7", "Soft paneer in a gently spiced spinach sauce with basmati rice.", "Paneer|200|g|3.20;Spinach|300|g|2.50;Rice|150|g|0.60;Onion|100|g|0.30;Cream|40|ml|0.45;Garam masala|6|g|0.20", "Cook rice according to its packet. Cube paneer and chop onion.", "Soften onion in a splash of water, add garam masala and spinach, and cook until wilted.~480", "Blend spinach mixture carefully, then return to the pan with paneer and cream.~300", "Simmer gently until paneer is hot throughout and serve over rice.~300");
        Add("Veggie Fried Rice", "Chinese", "Vegetarian", "egg,soy,wheat", 10, 15, "Easy", "photo-1603133872878-684f208fb84b", "A quick wok-style rice with egg, sweet peas and crunchy carrots.", "Cooked chilled rice|350|g|0.75;Eggs|2|pieces|0.80;Peas|100|g|0.40;Carrot|100|g|0.40;Soy sauce|20|ml|0.20;Vegetable oil|15|ml|0.15", "Use safely refrigerated cooked rice. Dice carrot and beat eggs.", "Heat oil, scramble eggs until fully set, and transfer to a plate.~120", "Stir-fry carrot and peas, then add rice. Heat until steaming throughout.~420", "Return eggs to the pan, add soy sauce and toss thoroughly.");
        Add("Sesame Tofu Noodles", "Korean", "Vegan", "soy,wheat,sesame", 15, 20, "Easy", "photo-1569718212165-3a8278d5f624", "Savoury noodles with seared tofu, sesame and tender greens.", "Wheat noodles|180|g|1.00;Firm tofu|250|g|2.40;Bok choy|200|g|1.50;Soy sauce|25|ml|0.25;Sesame oil|15|ml|0.45", "Drain and cube tofu. Wash bok choy thoroughly.", "Cook noodles according to their packet, then drain.~480", "Sear tofu in sesame oil until golden, then add bok choy and a splash of water.~600", "Toss noodles into the pan with soy sauce and serve hot.");
        Add("Roasted Vegetable Couscous", "Mediterranean", "Vegan", "wheat", 10, 30, "Easy", "photo-1512621776951-a57141f2eefd", "Colourful roasted vegetables and chickpeas folded through fluffy couscous.", "Couscous|150|g|0.80;Zucchini|200|g|0.90;Bell pepper|200|g|1.20;Cooked chickpeas|200|g|0.80;Olive oil|20|ml|0.40;Lemon|1|piece|0.50", "Heat oven to 210°C. Cut vegetables into even pieces.", "Toss vegetables and chickpeas in oil, spread on a tray and roast until tender.~1500", "Prepare couscous with boiling water according to packet instructions.~300", "Fluff couscous, fold in vegetables and chickpeas, and squeeze lemon over the top.");
        return dishes;
    }
}
